name: spec tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest #${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      env:
        CC: ${{ matrix.compiler }}
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cmake --build build
    - name: test
      run: |
        cd test
        ./run-spec-test.py

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cmake --build build
    #- name: test
    #  run: |
    #    cd test
    #    ./run-spec-test.py

  build-win:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        toolset: ["-T ClangCL", ""]

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.toolset }} ..
    - name: make
      run: |
        cmake --build build --config Release
        cp ./build/Release/wasm3.exe ./build/
    - name: test
      run: |
        cd test
        python run-spec-test.py
