name: spec tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        flags: ["", "-m32"]

    steps:
    - uses: actions/checkout@v1
    - name: Install multilib
      if: contains(matrix.flags, '-m32')
      run: sudo apt-get install gcc-multilib
    - name: Run CMake
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.flags }}
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        cmake --build build
    - name: Run spec tests
      run: |
        cd test
        ./run-spec-test.py
    - name: Run WASI tests
      run: |
        cd test
        ./run-wasi-test.py

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        cmake --build build
    - name: Run spec tests
      continue-on-error: true
      run: |
        cd test
        ./run-spec-test.py
    - name: Run WASI tests
      run: |
        cd test
        ./run-wasi-test.py

  build-win:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        toolset: ["-T ClangCL", ""]
        platform: ["-A Win32", ""]

    steps:
    - uses: actions/checkout@v1
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.platform }} ${{ matrix.toolset }} ..
    - name: Build
      run: |
        cmake --build build --config Release
        cp ./build/Release/wasm3.exe ./build/
    - name: Run spec tests
      continue-on-error: true
      run: |
        cd test
        python run-spec-test.py
